In [4]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
import numpy as np

In [10]:
#From Python Lists
arr=np.array([1,2,3])

In [14]:
arr_2d=np.array([[1,2,3],[4,5,6]])

In [7]:
#special arrays
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2,4))

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [18]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
np.random.rand(3,2)

array([[0.25129134, 0.91817011],
       [0.43922823, 0.43249155],
       [0.57635143, 0.77545001]])

In [17]:
np.random.randn(3,2)

array([[-0.73445607, -0.24339827],
       [-0.14754077,  0.57396194],
       [ 1.20568938, -1.68690665]])

In [20]:
arr=np.array([[1,2,3],[4,5,6]])

In [21]:
print(arr.shape)

(2, 3)


In [22]:
print(arr.ndim)

2


In [23]:
print(arr.size)

6


In [24]:
print(arr.dtype)

int64


In [25]:
#Basic math
a=np.array([1,2,3])

In [28]:
b=np.array([4,5,6])


In [29]:
a+b

array([5, 7, 9])

In [30]:
a*b

array([ 4, 10, 18])

In [31]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [38]:
#Matrix Multiplication
A=np.array([[1,2],[3,4]])

In [37]:
B=np.array([[5,6],[7,8]])

In [36]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [39]:
A @ B

array([[19, 22],
       [43, 50]])

In [40]:
#Aggregation
arr=np.array([1,2,3,4])

In [41]:
arr.sum()

np.int64(10)

In [42]:
arr.mean()

np.float64(2.5)

In [43]:
arr.max()

np.int64(4)

In [44]:
arr.min()

np.int64(1)

In [45]:
arr.std()

np.float64(1.118033988749895)

In [46]:
#1D Arrays
arr=np.array([1,2,3,4,5])

In [47]:
arr[0]

np.int64(1)

In [48]:
arr[1:4]

array([2, 3, 4])

In [49]:
arr[::2]

array([1, 3, 5])

In [51]:
#2D arrays
arr=np.array([[1,2,3],[4,5,6]])

In [52]:
arr[0,1]

np.int64(2)

In [53]:
arr[:,1]

array([2, 5])

In [54]:
arr[1,:2]

array([4, 5])

In [55]:
#Boolean Indexing
arr=np.array([1,2,3,4,5])

In [56]:
mask=arr>3

In [57]:
arr[mask]

array([4, 5])

In [66]:
#Reshape
arr = np.arange(6)

In [74]:
b = np.array([3,4])

In [78]:
np.concatenate ((a,b))

array([1, 2, 3, 3, 4])

In [80]:
#Stacking
np.vstack((a,b))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

In [81]:
np.hstack((a,b))

array([1, 2, 3, 3, 4])

In [ ]:
a + 5 # [6,7,8]

In [68]:
#Save to a file
np.save('array.npy',arr)

In [69]:
#load from a file
loaded_arr=np.load('array.npy')